cluster: openshift
action: "provision"
namespace: "{{ lookup('env','SERVICE_NAME') | default('galera', true) }}"
service_account: "{{ lookup('env','SERVICE_NAME') | default('galera', true) }}-replication-operator"
