- name: replication-apb playbook to provision the application
  strategy: debug
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: openshift
    playbook_debug: true
  - role: operator
    playbook_debug: true
  - role: galera
    playbook_debug: true
  vars:
    action: provision
    cluster: openshift
    